### ISSUE TITLE
Better not using key to generate work.bin file...

### ISSUE THREAD

**Issue by alpakeno** [TheRadziu/PkgDecrypt#3]
It's improper to create work.bin from key, each work.bin has a unique bytes in it even if the key is same...
Also the creator of the NoNPDRM confirms that.

**Comment by TheRadziu** [comment]
I already replied to this on reddit (in fact I didnt check git until now) but for any future readers: We are going to implement full 1:1 work.bin regeneration in a day or two. I also mentioned it already in proper issue I posted -> #1
